### ISSUE TITLE
"Add Transformation" button is missing when Date -> Date mapping is created

### ISSUE THREAD

**Issue by mmelko** [atlasmap/atlasmap#364]
Before there was possible to add Transformation between Date types such as "AddDays","AddSeconds". Currently there is no "Add Transformation" after [DATE-TYPE] ->[DATE-TYPE] mapping is created from UI .

**Comment by igarashitm** [comment]
@jpav did you look at UI when you added ANY_DATE support?

**Comment by jpav** [comment]
I did not, just the runtime. Is it not working in the UI?

**Comment by igarashitm** [comment]
#240 might help to find how it should be fixed

**Comment by jpav** [comment]
Well, I guess thanks for the solution, but I'm using these issues as a segue for me to learn the UI also, so I'd rather address them.

**Comment by mmelko** [comment]
works in UI but support of 'ANY_DATE' still missing in field actions: https://github.com/atlasmap/atlasmap/issues/381
